[settings]
experimental = true

[hooks]
enter = "if [ -f lefthook.yml ]; then lefthook install; fi"

[env]
GH_CONFIG_DIR="{{config_root}}/.gh"

[tasks.update]
description = "Update flake.lock"
run = "sudo nix flake update"

[tasks.rebuild]
description = "Apply nix-darwin configuration"
run = "sudo darwin-rebuild switch --impure --flake path:.#${USER}-aarch64-darwin --override-input user-config path:${HOME}/.config/nix"
depends_post = ["post-rebuild-agent-browser", "post-rebuild-lefthook"]

[tasks.post-rebuild-agent-browser]
hide = true
description = "Install agent-browser"
run = "agent-browser install"

[tasks.post-rebuild-lefthook]
hide = true
description = "Install lefthook hooks"
run = "lefthook install"

[tasks.brew]
description = "Update Homebrew cask"
run = "brew update && brew upgrade && brew cleanup"

[tasks.scan]
description = "Scan all repository files with betterleaks"
run = "betterleaks dir --no-banner --redact=20 ."
