[tasks.update]
description = "Update flake.lock"
run = "sudo nix flake update"

[tasks.rebuild]
description = "Apply nix-darwin configuration"
run = "sudo darwin-rebuild switch --impure --flake path:.#${USER}-aarch64-darwin --override-input user-config path:${HOME}/.config/nix"
depends_post = ["post-rebuild-agent-browser"]

[tasks.brew]
description = "Update Homebrew cask"
run = "brew update && brew upgrade && brew cleanup"
depends_post = ["post-rebuild-agent-browser"]

[tasks.post-rebuild-agent-browser]
hide = true
description = "Install agent-browser"
run = "agent-browser install"

[tasks."mise:install-global"]
description = "Install globally configured mise tools"
run = "mise install --global"
